version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    labels: [enhancement]
    groups:
      gradle-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "09:10"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    labels: [enhancement]
    groups:
      actions-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "09:20"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    labels: [enhancement]
    groups:
      docker-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
