spring:
  jackson:
    time-zone: Asia/Seoul
  application:
    name: server

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/${DB_NAME:hampouch}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
    baseline-version: 1
    validate-migration-naming: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:kuit-hampouch-kuit-hampouch-secret-key}
  access-token-expires-in-ms: ${JWT_ACCESS_TOKEN_EXPIRES_IN_MS:360000}
  refresh-token-expires-in-ms: ${JWT_REFRESH_TOKEN_EXPIRES_IN_MS:1209600000}

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_S3_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
